#!/usr/bin/env python
"""
Configuration for Dutch Real Estate Scraper

This file contains configuration settings that can be adjusted without modifying 
the core scraper code.
"""

import os
from typing import Dict, Any, List
from dotenv import load_dotenv
import random 

# Load environment variables from .env file if present
load_dotenv()

# Telegram bot settings
ENABLE_TELEGRAM = os.getenv("ENABLE_TELEGRAM", "True").lower() == "true"
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")

# Parse admin user IDs from environment
_admin_ids_str = os.getenv("TELEGRAM_ADMIN_USER_IDS", "")
TELEGRAM_ADMIN_USER_IDS = [int(uid.strip()) for uid in _admin_ids_str.split(",") if uid.strip().isdigit()]

# Notification settings
NOTIFICATION_INTERVAL = int(os.getenv("NOTIFICATION_INTERVAL", "300"))  # 5 minutes in seconds
MAX_NOTIFICATIONS_PER_USER_PER_DAY = int(os.getenv("MAX_NOTIFICATIONS_PER_USER_PER_DAY", "20"))
NOTIFICATION_BATCH_SIZE = int(os.getenv("NOTIFICATION_BATCH_SIZE", "50"))
NOTIFICATION_RETRY_ATTEMPTS = int(os.getenv("NOTIFICATION_RETRY_ATTEMPTS", "3"))

# Database configuration
DB_CONFIG = {
    "host": os.getenv("DB_HOST", "localhost"),
    "port": os.getenv("DB_PORT", "5432"),
    "database": os.getenv("DB_NAME", "realestate"),
    "user": os.getenv("DB_USER", "postgres"),
    "password": os.getenv("DB_PASSWORD", "postgres")
}

# Construct database connection string
DB_CONNECTION_STRING = f"postgresql://{DB_CONFIG['user']}:{DB_CONFIG['password']}@{DB_CONFIG['host']}:{DB_CONFIG['port']}/{DB_CONFIG['database']}"


# Default scan settings
DEFAULT_SCAN_INTERVAL = int(os.getenv("DEFAULT_SCAN_INTERVAL", "3600"))  # 1 hour in seconds
MAX_RESULTS_PER_SCAN = int(os.getenv("MAX_RESULTS_PER_SCAN", "100"))
MAX_CONCURRENT_REQUESTS = int(os.getenv("MAX_CONCURRENT_REQUESTS", "5"))
HTTP_TIMEOUT = float(os.getenv("HTTP_TIMEOUT", "30.0"))  # seconds
STOP_AFTER_NO_RESULT = os.getenv("STOP_AFTER_NO_RESULT", "True").lower() == "true"

# Default cities to scrape if none specified
DEFAULT_CITIES = os.getenv("DEFAULT_CITIES", "amsterdam,rotterdam,utrecht,den-haag,eindhoven").split(",")

# Default sources to scrape if none specified
DEFAULT_SOURCES = os.getenv("DEFAULT_SOURCES", "funda,pararius").split(",")

# Site-specific configurations
SITE_CONFIGS = {
    "funda": {
        "base_url": "https://www.funda.nl",
        "search_url_template": "https://www.funda.nl/zoeken/huur?selected_area=[\"{city}\"]&object_type=[\"house\",\"apartment\"]&sort=\"date_down\"",
        "min_interval": 10,  # TODO
    },
    "pararius": {
        "base_url": "https://www.pararius.com",
        "search_url_template": "https://www.pararius.com/apartments/{city}",
        "min_interval": 10,  # TODO
    },
    "vesteda": {
        "base_url": "https://www.vesteda.com",
        "search_url_template": "", # TODO
        "min_interval": 10,  # TODO
    },
    "rebo": {
        "base_url": "https://www.rebogroep.nl",
        "search_url_template": "", # TODO
        "min_interval": 10,  # TODO
    },
    "kamernet": {
        "base_url": "https://www.kamernet.nl",
        "search_url_template": "", # TODO
        "min_interval": 10,  # TODO
    },
    "regioamsterdam": {
        "base_url": "https://www.mijndak.nl",
        "search_url_template": "", # TODO
        "min_interval": 10,  # TODO
        "source_name": "regioamsterdam"
    },
    "regioutrecht": {
        "base_url": "https://www.mijndak.nl",
        "search_url_template": "", # TODO
        "min_interval": 10,  # TODO
        "source_name": "regioutrecht"
    },
    "regiogroningen": {
        "base_url": "https://www.mijndak.nl",
        "search_url_template": "", # TODO
        "min_interval": 10,  # TODO
        "source_name": "regiogroningen"
    },
    "regiogooienvecht": {
        "base_url": "https://www.mijndak.nl",
        "search_url_template": "", # TODO
        "min_interval": 10,  # TODO
        "source_name": "regiogooienvecht"
    },
    "regioalmere": {
        "base_url": "https://www.mijndak.nl",
        "search_url_template": "", # TODO
        "min_interval": 10,  # TODO
        "source_name": "regioalmere"
    },
    "regiomiddenholland": {
        "base_url": "https://www.mijndak.nl",
        "search_url_template": "", # TODO
        "min_interval": 10,  # TODO
        "source_name": "regiomiddenholland"
    },
    "regioeemvallei": {
        "base_url": "https://www.mijndak.nl",
        "search_url_template": "", # TODO
        "min_interval": 10,  # TODO
        "source_name": "regioeemvallei"
    },
    "regiobovengroningen": {
        "base_url": "https://www.mijndak.nl",
        "search_url_template": "", # TODO
        "min_interval": 10,  # TODO
        "source_name": "regiobovengroningen"
    },
    "regiowoonkeus": {
        "base_url": "https://www.mijndak.nl",
        "search_url_template": "", # TODO
        "min_interval": 10,  # TODO
        "source_name": "regiowoonkeus"
    },
    "regiowoongaard": {
        "base_url": "https://www.mijndak.nl",
        "search_url_template": "", # TODO
        "min_interval": 10,  # TODO
        "source_name": "regiowoongaard"
    },
    "regiohuiswaarts": {
        "base_url": "https://www.mijndak.nl",
        "search_url_template": "", # TODO
        "min_interval": 10,  # TODO
        "source_name": "regiohuiswaarts"
    },
    "huurwoningenappartement": {
        "base_url": "https://www.huurwoningen.nl",
        "search_url_template": "", # TODO
        "min_interval": 10,  # TODO
        "type": "appartement",
    },
    "huurwoningenhuis": {
        "base_url": "https://www.huurwoningen.nl",
        "search_url_template": "", # TODO
        "min_interval": 10,  # TODO
        "type": "huis",
    },
    "huurwoningenstudio": {
        "base_url": "https://www.huurwoningen.nl",
        "search_url_template": "", # TODO
        "min_interval": 10,  # TODO
        "type": "studio",
    },
    "huurwoningenkamer": {
        "base_url": "https://www.huurwoningen.nl",
        "search_url_template": "", # TODO
        "min_interval": 10,  # TODO
        "type": "kamer",
    },
    "bouwinvest": {
        "base_url": "https://www.wonenbijbouwinvest.nl",
        "search_url_template": "", # TODO
        "min_interval": 10,  # TODO
    },
    "vbt": {
        "base_url": "https://www.vbtverhuurmakelaars.nl",
        "search_url_template": "", # TODO
        "min_interval": 10,  # TODO
    },
    "123wonen": {
        "base_url": "https://www.123wonen.nl",
        "search_url_template": "", # TODO
        "min_interval": 10,  # TODO
    },
}

# Proxy settings
USE_PROXIES = os.getenv("USE_PROXIES", "False").lower() == "true"
PROXY_ROTATION_STRATEGY = os.getenv("PROXY_ROTATION_STRATEGY", "round_robin")  # Options: round_robin, random, fallback
MAX_PROXY_FAILURES = int(os.getenv("MAX_PROXY_FAILURES", "3"))

# Parse proxy list from environment
_proxy_list_str = os.getenv("PROXY_LIST", "")
PROXY_LIST = [p.strip() for p in _proxy_list_str.split(",") if p.strip()]

# Optional proxy provider settings
PROXY_PROVIDER = os.getenv("PROXY_PROVIDER", "")  # e.g., "luminati", "smartproxy", "brightdata"
PROXY_USERNAME = os.getenv("PROXY_USERNAME", "")
PROXY_PASSWORD = os.getenv("PROXY_PASSWORD", "")
PROXY_API_KEY = os.getenv("PROXY_API_KEY", "")
PROXY_API_ENDPOINT = os.getenv("PROXY_API_ENDPOINT", "")

# Function to format proxy URLs with credentials if provided
def get_formatted_proxy_list() -> List[str]:
    """Format proxy URLs with credentials if needed"""
    formatted_list = []
    
    # If specific provider credentials are given, use the appropriate format
    if PROXY_PROVIDER and PROXY_USERNAME and PROXY_PASSWORD:
        for proxy in PROXY_LIST:
            # Remove any existing authentication in the URL
            parts = proxy.split("@")
            host_part = parts[-1]
            
            if PROXY_PROVIDER.lower() == "luminati":
                # Format: http://username-session-{ip}:password@zproxy.lum-superproxy.io:22225
                formatted = f"http://{PROXY_USERNAME}-session-{random.randint(10000, 99999)}:{PROXY_PASSWORD}@{host_part}"
            else:
                # Default format: http://username:password@host:port
                formatted = f"http://{PROXY_USERNAME}:{PROXY_PASSWORD}@{host_part}"
            
            formatted_list.append(formatted)
    else:
        # Use proxy list as is
        formatted_list = PROXY_LIST
    
    return formatted_list

# Override any config settings with environment variables
def update_site_config_from_env():
    """Update site configurations from environment variables if present"""
    for site in SITE_CONFIGS:
        site_prefix = f"SITE_{site.upper()}_"
        for key in SITE_CONFIGS[site]:
            env_key = f"{site_prefix}{key.upper()}"
            if os.getenv(env_key):
                # Handle different types
                if isinstance(SITE_CONFIGS[site][key], int):
                    SITE_CONFIGS[site][key] = int(os.getenv(env_key))
                elif isinstance(SITE_CONFIGS[site][key], float):
                    SITE_CONFIGS[site][key] = float(os.getenv(env_key))
                elif isinstance(SITE_CONFIGS[site][key], bool):
                    SITE_CONFIGS[site][key] = os.getenv(env_key).lower() == "true"
                else:
                    SITE_CONFIGS[site][key] = os.getenv(env_key)

# Call the update function to apply environment variable overrides
update_site_config_from_env()

# Replace this with distinct selection from DB later when database is larger
ALL_CITIES = set(["'S GRAVENMOER","'S HERTOGENBOSCH","'S-GRAVELAND","'S-GRAVENDEEL","'S-GRAVENHAGE ","'S-GRAVENMOER","'S-GRAVENPOLDER","'S-GRAVENZANDE","'S-HEER ARENDSKERKE","'S-HEER HENDRIKSKINDEREN","'S-HEERENBERG","'S-HEERENHOEK","'T GOY","'T HARDE","'T LOO OLDEBROEK","'T VELD","'T WAAR","'T ZAND","'T ZANDT","1E EXLOËRMOND","2E EXLOERMOND","AADORP","AAGTEKERKE","AALDEN","AALSMEER","AALSMEERDERBRUG","AALST","AALTEN","AARDENBURG","AARLANDERVEEN","AARLE-RIXTEL","ABBENES","ABCOUDE","ACHLUM","ACHTERVELD","ACHTHUIZEN","ACQUOY","ADORP","AERDENHOUT","AFFERDEN","AKERSLOOT","AKKRUM","ALBERGEN","ALBLASSERDAM","ALDE LEIE","ALDEBOARN","ALDWALD","ALEM","ALKMAAR","ALLINGAWIER","ALMELO","ALMERE","ALMKERK","ALPHEN","ALPHEN NB","ALPHEN AAN DEN RIJN","ALTEVEER","AMBT DELDEN","AMEIDE","AMERICA","AMERONGEN","AMERSFO","AMERSFOORT","AMMERZODEN","AMSTELVEEN","AMSTENRADE","AMSTERDAM","ANDEL","ANDEREN","ANDIJK","ANGEREN","ANGERLO","ANKEVEEN","ANLOO","ANNA PAULOWNA","ANNEN","ANNERVEENSCHEKANAAL","APELDOORN","APPELSCHA","APPELTERN","APPINGEDAM","ARCEN","ARKEL","ARNEMUIDEN","ARNHEM","ARUM","ASCH","ASPEREN","ASSEN","ASSENDELFT","ASTEN","AUSTERLITZ","AVENHORN","AXEL","AZEWIJN","BAAMBRUGGE","BAARLE-NASSAU","BAARLO","BAARLO LB","BAARN","BAD NIEUWESCHANS","BADHOEVEDORP","BAEXEM","BAFLO","BAKEL","BAKHUIZEN","BAKKEVEEN","BALK","BALKBRUG","BANHOLT","BARCHEM","BARENDRECHT","BARGER-COMPASCUUM","BARNEVELD","BATENBURG","BATHMEN","BAVEL","BAVEL (GEM. BREDA)","BEDUM","BEEGDEN","BEEK","BEEK (GEM. BERG EN DAL)","BEEK (GEM. MONTFERLAND)","BEEK LB","BEEK EN DONK","BEEKBERGEN","BEERS","BEERZERVELD","BEESD","BEESEL","BEETS","BEETSTERZWAAG","BEILEN","BEINSDORP","BELFELD","BELLINGWOLDE","BELT-SCHUTSLOOT","BELTRUM","BEMELEN","BEMMEL","BENEDEN-LEEUWEN","BENNEBROEK","BENNEKOM","BENSCHOP","BENTELO","BENTHUIZEN","BENTVELD","BERG EN DAL","BERG EN TERBLIJT","BERGAMBACHT","BERGEIJK","BERGEN","BERGEN NH","BERGEN AAN ZEE","BERGEN OP ZOOM","BERGENTHEIM","BERGHAREN","BERGHEM","BERGSCHENHOEK","BERKEL EN RODENRIJS","BERKEL-ENSCHOT","BERKHOUT","BERLICUM","BERLTSUM","BEST","BEUGEN","BEUNINGEN","BEUNINGEN GLD","BEUSICHEM","BEVERWIJK","BIDDINGHUIZEN","BIERVLIET (GEM. TERNEUZEN)","BIEST-HOUTAKKER","BILTHOVEN","BINGELRADE","BITGUM","BITGUMMOLE","BLADEL","BLARICUM","BLAUWESTAD","BLAUWHUIS","BLEISWIJK","BLESKENSGRAAF CA","BLIJE","BLITTERSWIJCK","BLOEMENDAAL","BLOKKER","BLOKZIJL","BOAZUM","BOCHOLTZ","BODEGRAVEN","BOEKEL","BOELENSLAAN","BOERDONK","BOIJL","BOLSWARD","BOORNZWAAG","BORCULO","BORGER","BORN","BORNE","BORNERBROEK","BOSCH EN DUIN","BOSKAMP","BOSKANT","BOSKOOP","BOSSCHENHOOFD","BOURTANGE","BOVEN-LEEUWEN","BOVENKARSPEL","BOVENSMILDE","BOXMEER","BOXTEL","BRAAMT","BRAKEL","BRANDWIJK","BREDA","BREDEVOORT","BREEZAND","BRESKENS","BREUKELEN","BREUKELEN UT","BREUKELEVEEN","BRIELLE","BRITSUM","BROEK IN WATERLAND","BROEK OP LANGEDIJK","BROEKHUIZEN","BROEKHUIZENVORST","BROEKLAND","BROEKSTERWALD","BROUWERSHAVEN","BRUCHEM","BRUCHTERVELD","BRUINISSE","BRUMMEN","BRUNSSUM","BUCHTEN","BUDEL","BUDEL-DORPLEIN","BUDEL-SCHOOT","BUGGENUM","BUITENKAAG","BUITENPOST","BUNDE","BUNNIK","BUNSCHOTEN-SPAKENBURG","BURDAARD","BUREN","BURGERBRUG","BURGERVEEN","BURGH-HAAMSTEDE","BURGUM","BURUM","BUSSUM","BUURMALSEN","CADIER EN KEER","CADIER EN KEER","CADZAND","CALLANTSOOG","CAPELLE AAN DEN IJSSEL","CASTEREN","CASTRICUM","CHAAM","CLINGE","COEVORDEN","COLIJNSPLAAT","COLMSCHATE","COTHEN","CROMVOIRT","CRUQUIUS","CUIJK","CULEMBORG","DZ AMSTERDAM","DAARLERVEEN","DALEM","DALEN","DALERPEEL","DALFSEN","DAMWALD","DAMWÂLD","DE BILT","DE BULT","DE COCKSDORP","DE GOORN","DE GROEVE","DE HEEN","DE KNIPE","DE KOOG","DE KRIM","DE KWAKEL","DE LIER","DE LUTTE","DE MEERN","DE MOER","DE MORTEL","DE RIJP","DE RIPS","DE SCHIPHORST","DE STEEG","DE TIKE","DE WESTEREEN","DE WIJK","DE WILP","DE ZILK","DEDEMSVAART","DEDGUM","DEINUM","DELDEN","DELFGAUW","DELFSTRAHUIZEN","DELFT","DELFZIJL","DELWIJNEN","DEMEN","DEN ANDEL","DEN BOMMEL","DEN BOSCH","DEN BURG","DEN DOLDER","DEN DUNGEN","DEN HAAG","DEN HAM","DEN HELDER","DEN HOORN","DEN HORN","DEN ILP","DEN OEVER","DEN BOSCH","DENEKAMP","DEURNE","DEURNINGEN","DEURNINGEN (GEM. DINKELLAND)","DEVENTER","DIDAM","DIEMEN","DIEPENHEIM","DIEPENVEEN","DIEREN","DIESSEN","DIEVER","DINTELOORD","DINXPERLO","DIRKSLAND","DODEWAARD","DOENRADE","DOESBURG","DOETINCHEM","DOKKUM","DOMBURG","DONGEN","DONGJUM","DONKERBROEK","DOORN","DOORNSPIJK","DOORWERTH","DORDRECHT","DORST","DRACHTEN","DRACHTSTERCOMPAGNIE","DREMPT","DREUMEL","DRIEBERGEN","DRIEBERGEN-RIJSENBURG","DRIEBERGEN-RIJSENB","DRIEBERGEN-RIJSENBURG","DRIEBRUGGEN","DRIEHUIS","DRIEHUIS NH","DRIEHUIZEN","DRIEL","DRIEZUM","DROGEHAM","DRONGELEN","DRONRYP","DRONTEN","DRUNEN","DRUTEN","DUIVEN","DUIVENDRECHT","DUIZEL","DUSSEN","DWINGELOO","EARNEWÂLD","EASTEREIN","EASTERLITTENS","EASTERMAR","EASTERNIJTSJERK","EASTERWIERRUM","ECHT","ECHTELD","ECHTENERBRUG","ECK EN WIEL","ECKELRADE","EDAM","EDE","EDE GLD","EDERVEEN","EEDE","EEFDE","EELDE","EELDERWOLDE","EEMDIJK","EEMNES","EEN","EENRUM","EERBEEK","EERDE","EERSEL","EETHEN","EGMOND AAN ZEE","EGMOND AAN DEN HOEF","EGMOND-BINNEN","EIBERGEN","EIJSDEN","EINDHOVEN","EINIGHAUSEN","ELBURG","ELEVELD","ELIM","ELL","ELLECOM","ELSENDORP","ELSHOUT","ELSLOO","ELSPEET","ELST","ELST UT","ELST GLD","EMMELOORD","EMMEN","EMMER-COMPASCUUM","EMPE","EMPEL","ENGELEN","ENKHUIZEN","ENS","ENSCHEDE","ENSPIJK","ENTER","EPE","EPSE","ERICA","ERICHEM","ERM","ERMELO","ERP","ESBEEK","ESCH","ESCHAREN","EST","ETTEN","ETTEN-LEUR","EVERDINGEN","EWIJK","EXLOO","EXMORRA","EYGELSHOVEN","EYS","FARMSUM","FEANWALDEN","FEANWÂLDEN","FERWERT","FIJNAART","FLUITENBERG","FOXHOL","FOXWOLDE","FRANEKER","FRIESCHEPALEN","GAANDEREN","GALDER","GAMEREN","GARDEREN","GARMERWOLDE","GARNWERD","GARSTHUIZEN","GARYP","GASSEL","GASSELTE","GASSELTERNIJVEEN","GASTEL","GAUW","GEERSDIJK","GEERTRUIDENBERG","GEERVLIET","GEESBRUG","GEESTEREN","GEFFEN","GELDERMALSEN","GELDROP","GELEEN","GELLICUM","GELSELAAR","GEMERT","GENDRINGEN","GENDT","GENEMUIDEN","GENNEP","GERWEN","GEULLE","GIESBEEK","GIESSEN","GIESSENBURG","GIETEN","GIETERVEEN","GIETHOORN","GILZE","GLIMMEN","GOEDEREEDE","GOES","GOINGARIJP","GOIRLE","GOOR","GORINCHEM","GORREDIJK","GORSSEL","GOUDA","GOUDERAK","GOUDRIAAN","GOUTUM","GRAFT","GRAMSBERGEN","GRASHOEK","GRATHEM","GRAVE","GREVENBICHT","GRIENDTSVEEN","GRIJPSKERK","GRIJPSKERKE","GROEDE","GROENEKAN","GROENLO","GROESBEEK","GROET","GROLLOO","GRONINGEN","GRONSVELD","GROOT-AMMERS","GROOTEBROEK","GROOTSCHERMER","GROU","GRUBBENVORST","GULPEN","GYTSJERK","HAAFTEN","HAAKSBERGEN","HAALDEREN","HAAREN","HAARLE (GEM. TUBBERGEN)","HAARLE GEM HELLENDOORN","HAARLEM","HAARSTEEG","HAASTRECHT","HAELEN","HAGESTEIN","HAGHORST","HALFWEG","HALLE","HALLUM","HALSTEREN","HANDEL","HANK","HANSWEERT","HANTUM","HAPERT","HAPS","HARBRINKHOEK","HARDENBERG","HARDERWIJK","HARDINXVELD-GIESSENDAM","HAREN","HAREN GN","HARFSEN","HARKEMA","HARKSTEDE","HARKSTEDE (GEM. MIDDEN-GRONINGEN)","HARLINGEN","HARMELEN","HARREVELD","HARSKAMP","HASKERDIJKEN","HASKERHORNE","HASSELT","HATTEM","HATTEMERBROEK","HAULERWIJK","HAVELTE","HAZERSWOUDE-DORP","HAZERSWOUDE-RIJNDIJK","HEDEL","HEEG","HEEL","HEELSUM","HEEMSKERK","HEEMSTEDE","HEENVLIET","HEERDE","HEERENVEEN","HEEREWAARDEN","HEERHUGOWAARD","HEERJANSDAM","HEERLE","HEERLEN","HEESCH","HEESWIJK-DINTHER","HEETEN","HEEZE","HEI- EN BOEICOP","HEIDE","HEIJNINGEN","HEILOO","HEINENOORD","HEINKENSZAND","HEINO","HEKELINGEN","HEKENDORP","HELDEN","HELLENDOORN","HELLEVOETSLUIS","HELLOUW","HELMOND","HELVOIRT","HEMELUM","HENDRIK- IDO-AMBACHT","HENDRIK-IDO-AMBACHT","HENDRIK-IDO-AMBACHT","HENGELO","HENGELO(GLD)","HENGEVELDE","HENSBROEK","HERKENBOSCH","HERPEN","HERTEN","HERTME","HERVELD","HERWIJNEN","HERXEN","HETEREN","HEUKELUM","HEUMEN","HEUSDEN","HEUSDEN (GEM. ASTEN)","HEUSDEN (GEM. HEUSDEN)","HEYEN","HEYTHUYSEN","HEZINGEN","HEZINGEN-MANDER-VASSE","HIERDEN","HIJUM","HILLEGOM","HILVARENBEEK","HILVERSUM","HINDELOOPEN","HIPPOLYTUSHOEF","HITZUM","HOEDEKENSKERKE","HOEF EN HAAG","HOEK","HOEK VAN HOLLAND","HOENDERLOO","HOENDERLOO (GEM. APELDOORN)","HOENSBROEK","HOENZADRIEL","HOEVELAKEN","HOEVEN","HOGE HEXEL","HOLLANDSCHE RADING","HOLLANDSCHEVELD","HOLTEN","HOLTUM","HOLWERD","HOLWERT","HOLWIERDE","HONSELERSDIJK","HOOFDDORP","HOOG-KEPPEL","HOOGE ZWALUWE","HOOGELOON","HOOGERHEIDE","HOOGERSMILDE","HOOGEVEEN","HOOGEZAND","HOOGHALEN","HOOGKARSPEL","HOOGLAND","HOOGLANDERVEEN","HOOGMADE","HOOGVLIET","HOOGVLIET ROTTERDAM","HOOGWOUD","HOORN","HOORN NH","HOORNAAR","HORN","HORSSEN","HORST","HOUTEN","HOUTIGEHAGE","HOUWERZIJL","HUIS TER HEIDE","HUISSEN","HUIZEN","HULSBERG","HULSEL","HULSHORST","HULST","HUMMELO","HUNSEL","HURDEGARYP","HURWENEN","IJHORST","IJLST","IJMUIDEN","IJSSELMUIDEN","IJSSELSTEIN","IJZENDIJKE","IJZENDOORN","IE","IJSSELSTEIN","ILPENDAM","INGBER","INGEN","IT HEIDENSKIP","JAARSVELD","JABEEK","JELSUM","JIRNSUM","JISP","JISTRUM","JORWERT","JOURE","JUBBEGA","JULIANADORP","JUTRIJP","KAAG","KAATSHEUVEL","KAMERIK","KAMPEN","KAMPERLAND","KAPEL-AVEZAATH (GEM. BUREN)","KAPELLE","KATWIJK","KATWOUDE","KEDICHEM","KEIJENBORG","KELDONK","KELPEN-OLER","KERK-AVEZAATH","KERK-AVEZAATH (GEM. BUREN)","KERKDRIEL","KERKRADE","KERKWIJK","KESSEL","KESSEL LB","KESTEREN","KIEL-WINDEWEER","KILDER","KIMSWERD","KLAASWAAL","KLARENBEEK (APELDOORN)","KLARENBEEK (VOORST)","KLAZIENAVEEN","KLEIN ZUNDERT","KLEVE","KLIMMEN","KLOETINGE","KLOETINGE (GEM. GOES)","KLOOSTERBUREN","KLOOSTERHAAR","KLUNDERT","KNEGSEL","KOCKENGEN","KOEKANGE","KOEWACHT","KOLHAM","KOLHORN","KOLLUM","KOLLUMERPOMP","KOLLUMERSWEACH","KONINGSBOSCH","KONINGSLUST","KOOG AAN DE ZAAN","KOOTWIJKERBROEK","KORENVELD","KORTENHOEF","KORTGENE","KOUDEKERK AAN DEN RIJN","KOUDEKERKE","KOUDUM","KOUFURDERRIGE","KRABBENDIJKE","KRIMPEN AAN DEN IJSSEL","KRIMPEN AAN DE LEK","KRIMPEN AAN DEN IJSSEL","KROMMENIE","KRONENBERG","KROPSWOLDE","KRUININGEN","KUDELSTAART","KWADIJK","KWINTSHEUL","LAAG ZUTHEM","LAGE MIERDE","LAGE VUURSCHE","LAGE ZWALUWE","LANDGRAAF","LANDSMEER","LANGBROEK","LANGELILLE","LANGENBOOM","LANGERAK","LANGEVEEN-BRUINEHAAR","LANGEWEG","LANGWEER","LAREN","LATHUM","LEDEACKER","LEEK","LEENDE","LEENS","LEERBROEK","LEERDAM","LEERSUM","LEEUWARDEN","LEIDEN","LEIDERDORP","LEIDSCHENDAM","LEIMUIDEN","LEKKERKERK","LELYSTAD","LEMELE","LEMELERVELD","LEMIERS","LEMMER","LENGEL","LENT","LEPELSTRAAT","LEUNEN","LEUSDEN","LEUTH","LEVEROY","LEWEDORP","LEXMOND","LICHTENVOORDE","LIEMPDE","LIENDEN","LIEREN","LIEROP","LIESHOUT","LIESSEL","LIJNDEN","LIMBRICHT","LIMMEN","LINDE","LINDEN","LINNE","LINSCHOTEN","LIPPENHUIZEN","LISSE","LISSERBROEK","LITH","LITHOIJEN","LOBITH","LOCHEM","LOENEN GLD","LOENEN AAN DE VECHT","LOENERSLOOT","LOLLUM","LOO (GEM. DUIVEN)","LOON OP ZAND","LOOSBROEK","LOOSDRECHT","LOPIK","LOPIKERKAPEL","LOPPERSUM","LOSSER","LOTTUM","LUNTEREN","LUTJEGAST","LUTTELGEEST","LUTTEN","LUTTENBERG","LUYKSGESTEL","MAARHEEZE","MAARN","MAARSBERGEN","MAARSSEN","MAARSSENBROEK","MAARTENSDIJK","MAASBOMMEL","MAASBRACHT","MAASBREE","MAASDAM","MAASDIJK","MAASLAND","MAASSLUIS","MAASTRICHT","MACHAREN","MADE","MAKKUM","MAKKUM FR","MALDEN","MANTGUM","MAREN-KESSEL","MARGRATEN","MARIAHOUT","MARIAPAROCHIE-HARBRINKHOEK","MARIENBERG","MARIËNVELDE","MARKELO","MARKEN","MARRUM","MARSUM","MARUM","MAURIK","MEDEMBLIK","MEERKERK","MEERSSEN","MEEUWEN","MEGCHELEN","MEGEN","MEIJEL","MELDERSLO","MELICK","MELISSANT","MENAAM","MEPPEL","MERKELBEEK","METEREN","METERIK","METSLAWIER","MHEER","MIDDELBURG","MIDDELHARNIS","MIDDELSTUM","MIDDENBEEMSTER","MIDDENMEER","MIDLAREN","MIDWOLDA","MIDWOUD","MIERLO","MIJDRECHT","MIJNSHEERENLAND","MILL","MINNERTSGA","MOERDIJK","MOERGESTEL","MOERKAPELLE","MOLENHOEK","MOLENHOEK LB","MONNICKENDAM","MONSTER","MONTFOORT","MONTFORT","MOOK","MOORDRECHT","MOORVELD","MUIDEN","MUIDERBERG","MUNNEKEZIJL","MUNSTERGELEEN","MUSSEL","MUSSELKANAAL","NAALDWIJK","NAARDEN","NAGELE","NEDERHEMERT","NEDERHORST DEN BERG","NEDERWEERT","NEEDE","NEER","NEERITTER","NETERSEL","NIBBIXWOUD","NIETAP","NIEUW NAMEN","NIEUW-AMSTERDAM","NIEUW-BALINGE","NIEUW-BEIJERLAND","NIEUW-BUINEN","NIEUW-DORDRECHT","NIEUW-LEKKERLAND","NIEUW-RODEN","NIEUW-SCHOONEBEEK","NIEUW-VENNEP","NIEUW-VOSSEMEER","NIEUW-WEERDINGE","NIEUWAAL","NIEUWDORP","NIEUWE NIEDORP","NIEUWE PEKELA","NIEUWE-TONGE","NIEUWEGEIN","NIEUWEHORNE","NIEUWENDIJK","NIEUWERBRUG AAN DEN RIJN","NIEUWERKERK","NIEUWERKERK A/D IJSSEL","NIEUWERKERK A/D IJSSEL","NIEUWERKERK AAN DEN IJSSEL","NIEUWEROORD","NIEUWERSLUIS","NIEUWKOOP","NIEUWKUIJK","NIEUWLAND","NIEUWLANDE","NIEUWLEUSEN","NIEUWOLDA","NIEUWPOORT","NIEUWSTADT","NIEUWVEEN","NIGTEVECHT","NIJ BEETS","NIJEMIRDUM","NIJEVEEN","NIJKERK","NIJKERK GLD","NIJKERKERVEEN","NIJMEGEN","NIJNSEL","NIJVERDAL","NISPEN","NISTELRODE","NOARDBURGUM","NOOITGEDACHT","NOORBEEK","NOORD-SCHARWOUDE","NOORDBROEK","NOORDEINDE","NOORDELOOS","NOORDEN","NOORDGOUWE","NOORDHOEK","NOORDSCHESCHUT","NOORDWIJK","NOORDWIJKERHOUT","NOORDWOLDE","NOOTDORP","NORG","NUENEN","NULAND","NUMANSDORP","NUNSPEET","NUTH","OBBICHT","OBDAM","OCHTEN","ODIJK","ODILIAPEEL","ODOORN","ODOORNERVEEN","OEFFELT","OEGSTGEEST","OENE","OENTSJERK","OFFINGAWIER","OHÉ EN LAAK","OIJEN","OIRLO","OIRSBEEK","OIRSCHOT","OISTERWIJK","OLDEBERKOOP","OLDEBROEK","OLDEMARKT","OLDENZAAL","OLST","OMMEN","OMMEREN","ONDERDENDAM","ONNEN","ONSTWEDDE","OOLTGENSPLAAT","OOST WEST EN MIDDELBEERS","OOST-SOUBURG","OOSTBURG","OOSTEIND","OOSTERBEEK","OOSTERBIERUM","OOSTERBLOKKER","OOSTEREND NH","OOSTERHESSELEN","OOSTERHOUT","OOSTERHOUT NB","OOSTERLAND","OOSTERWOLDE","OOSTERWOLDE FR","OOSTERZEE","OOSTHEM","OOSTKAPELLE","OOSTKNOLLENDAM","OOSTRUM","OOSTVOORNE","OOSTWOLD","OOSTWOUD","OOSTZAAN","OOTMARSUM","OPEINDE","OPENDE","OPHEMERT","OPHEUSDEN","OPIJNEN","OPLOO","OPMEER","OPPENHUIZEN","OPPERDOES","OSPEL","OSS","OSSENDRECHT","OTTERLO","OTTERSUM","OTTOLAND","OUD ADE","OUD GASTEL","OUD-ALBLAS","OUD-BEIJERLAND","OUD-VOSSEMEER","OUDDORP","OUDE NIEDORP","OUDE PEKELA","OUDE WETERING","OUDE-TONGE","OUDEBILDTZIJL","OUDEGA","OUDEGA (GEM. SMALLINGERLAND)","OUDEGA DE FRYSKE MARREN","OUDEGA SUDWEST-FRYSLAN","OUDEHASKE","OUDELANDE","OUDEMIRDUM","OUDENBOSCH","OUDENHOORN","OUDERKERK AAN DE AMSTEL","OUDERKERK AAN DEN IJSSEL","OUDESCHILD","OUDESCHOOT","OUDEWATER","OUDHEUSDEN","OUDKARSPEL","OUDKARSPEL (GEM. DIJK EN WAARD)","OUDORP","OUDORP NH","OVERDINKEL","OVERLOON","OVERVEEN","OVEZANDE","PAASLOO","PANNERDEN","PANNINGEN","PAPENDRECHT","PAPENHOVEN","PATERSWOLDE","PEIZE","PERNIS","PERNIS ROTTERDAM","PESSE","PETTEN","PHILIPPINE","PIERSHIL","PIJNACKER","POEDEROIJEN","POELDIJK","POLSBROEK","POORTUGAAL","POORTVLIET","POSTERHOLT","PRINSENBEEK","PUIFLIJK","PURMEREND","PURMERLAND","PUTH","PUTTE","PUTTEN","PUTTERSHOEK","ROTTERDAM","RAALTE","RAAMSDONK","RAAMSDONKSVEER","RANDWIJK","RANSDAAL","RASQUERT","RAVENSTEIN","RAVENSWAAIJ","READTSJERK","REDUZUM","REEK","REEUWIJK","REKKEN","RENKUM","RENSWOUDE","RESSEN","REUSEL","REUVER","RHEDEN","RHENEN","RHENOY","RHOON","RIDDERKERK","RIED","RIEL","RIETHOVEN","RIETMOLEN","RIJEN","RIJKEVOORT","RIJNSATERWOUDE","RIJNSBURG","RIJPWETERING","RIJSBERGEN","RIJSENHOUT","RIJSSEN","RIJSWIJK","RIJSWIJK (GLD)","RIJSWIJK ZH","RILLAND","RINSUMAGEAST","ROCKANJE","RODEN","ROELOFARENDSVEEN","ROERMOND","ROGGEL","ROHEL","ROLDE","ROODESCHOOL","ROOSENDAAL","ROOSTEREN","ROSMALEN","ROSSUM","ROTTERDAM","ROTTERDAM ","ROTTEVALLE","ROUVEEN","ROZENBURG","ROZENDAAL","RUCPHEN","RUINEN","RUINERWOLD","RUMPT","RUTTEN","RUURLO","RYPTSJERK","SOESTERBERG","SAASVELD","SAMBEEK","SANTPOORT-NOORD","SANTPOORT-ZUID","SAPPEMEER","SAS VAN GENT","SASSENHEIM","SAUWERD","SCHAGEN","SCHAGERBRUG","SCHAIJK","SCHALKHAAR","SCHALKWIJK","SCHARDAM","SCHARNEGOUTUM","SCHARSTERBRUG","SCHARWOUDE","SCHEEMDA","SCHELLUINEN","SCHERMERHORN","SCHERPENISSE","SCHERPENZEEL","SCHIEDAM","SCHIJNDEL","SCHILDWOLDE","SCHIMMERT","SCHIN OP GEUL","SCHIN OP GEUL","SCHINNEN","SCHINVELD","SCHIPBORG","SCHIPLUIDEN","SCHOONDIJKE","SCHOONEBEEK","SCHOONHOVEN","SCHOONOORD","SCHOONREWOERD","SCHOORL","SEROOSKERKE ","SEROOSKERKE (GEM. SCHOUWEN-DUIVELAND)","SEROOSKERKE (GEM. VEERE)","SEVENUM","SEXBIERUM","SIBCULO","SIBCULO (GEM. HARDENBERG)","SIDDEBUREN","SIEBENGEWALD","SILVOLDE","SIMONSHAVEN","SIMPELVELD","SINDEREN","SINT ANTHONIS","SINT GEERTRUID","SINT HUBERT","SINT JANSKLOOSTER","SINT JANSTEEN","SINT JOOST","SINT MAARTEN","SINT MAARTENSBRUG","SINT NICOLAASGA","SINT ODILIËNBERG","SINT PANCRAS","SINT PHILIPSLAND","SINT JOOST","SINT-ANNALAND","SINT-MAARTENSDIJK","SINT-MICHIELSGESTEL","SINT-OEDENRODE","SINTJOHANNESGA","SITTARD","SLAGHAREN","SLEEN","SLEEUWIJK","SLIEDRECHT","SLOCHTEREN","SLOOTDORP","SLOTEN FR","SLUIS","SLUISKIL","SMILDE","SNEEK","SNELREWAARD","SOERENDONK","SOEST","SOESTERBERG","SOMEREN","SOMEREN-EIND","SOMMELSDIJK","SON EN BREUGEL","SONDEL","SPAARNDAM","SPAARNDAM GEM. HAARLEM","SPANBROEK","SPAUBEEK","SPIERDIJK","SPIJK (GEM. WEST BETUWE)","SPIJKENISSE","SPRANG-CAPELLE","SPRUNDEL","ST. WILLEBRORD","ST.-ANNAPAROCHIE","ST.-JACOBIPAROCHIE","STAD AAN 'T HARINGVLIET","STADSKANAAL","STAMPERSGAT","STANDDAARBUITEN","STAPHORST","STAVENISSE","STAVOREN","STEDUM","STEENBERGEN","STEENDEREN","STEENWIJK","STEENWIJKERWOLD","STEGEREN","STEGGERDA","STEIN","STELLENDAM","STERKSEL","STEVENSBEEK","STEVENSWEERT","STEYL","STIENS","STITSWERD","STOLWIJK","STOMPETOREN","STOUTENBURG","STRAMPROY","STREEFKERK","STRIJBEEK","STRIJEN","STROE","SUMAR","SURHUISTERVEEN","SURHUIZUM","SUSTEREN","SUWALD","SWALMEN","SWEAGERBOSK","SWIFTERBANT","SWOLGEN","TAARLO","TEGELEN","TEN BOER","TEN POST","TER AAR","TER APEL","TER HEIJDE","TERBORG","TERHEIJDEN","TERHERNE","TERNAARD","TERNEUZEN","TERSCHUUR","TERSOAL","TERWISPEL","TERWOLDE","TETERINGEN","TEUGE","THOLEN","THORN","TIEL","TIENDEVEEN","TIENDEVEEN (GEM. HOOGEVEEN)","TIENHOVEN","TIENHOVEN AAN DE LEK","TIENRAY","TIJNJE","TILBURG","TJERKGAAST","TJERKWERD","TOLBERT","TOLDIJK","TONDEN","TRICHT","TUBBERGEN","TUITJENHORN","TUK","TULL EN 'T WAAL","TWELLO","TWIJZELERHEIDE","TWISK","TYNAARLO","TZUM","TZUMMARUM","UBBERGEN","UDDEL","UDEN","UDENHOUT","UFFELTE","UGCHELEN","UITDAM","UITGEEST","UITHOORN","UITHUIZEN","UITHUIZERMEEDEN","ULESTRATEN","ULFT","ULICOTEN","ULRUM","ULVENHOUT","ULVENHOUT (GEM. BREDA)","URETERP","URMOND","URSEM (GEM. ALKMAAR)","UTRECHT","VAALS","VAASSEN","VALBURG","VALKENBURG","VALKENBURG (ZUID HOLLAND)","VALKENBURG LB","VALKENSWAARD","VALTHE","VALTHERMOND","VARSSEVELD","VEEN","VEENDAM","VEENENDAAL","VEENHUIZEN","VEENINGEN","VEENOORD","VEERE","VEGHEL","VELDDRIEL","VELDEN","VELDHOVEN","VELP","VELSEN-NOORD","VELSEN-ZUID","VELSERBROEK","VEN ZELDERHEIDE","VENHORST","VENHUIZEN","VENLO","VENLO-BLERICK","VENRAY","VESSEM","VIANEN","VIERAKKER","VIERPOLDERS","VIJFHUIZEN","VIJLEN","VINKEL","VINKEL (GEM. DEN BOSCH)","VINKEVEEN","VLAARDINGEN","VLAGTWEDDE","VLEDDER","VLEUTEN","VLIJMEN","VLISSINGEN","VLODROP","VOERENDAAL","VOGELENZANG","VOGELWAARDE","VOLENDAM","VOLKEL","VOLLENHOVE","VOORBURG","VOORHOUT","VOORSCHOTEN","VOORST","VOORST (GEM. VOORST)","VOORTHUIZEN","VORDEN","VORSTENBOSCH","VREELAND","VRIES","VRIEZENVEEN","VROOMSHOOP","VUGHT","VUREN","VYLEN","WAALRE","WAALWIJK","WAARDENBURG","WAARDER","WACHTUM","WADDINXVEEN","WADENOIJEN","WAGENBERG","WAGENINGEN","WALTERSWALD","WAMEL","WANNEPERVEEN","WANROIJ","WANSSUM","WAPENVELD","WAPSERVEEN","WARFFUM","WARFSTERMOLEN","WARMENHUIZEN","WARMOND","WARNS","WARNSVELD","WARTEN","WASKEMEER","WASPIK","WASSENAAR","WATERGANG","WATERINGEN","WAVERVEEN","WEERSELO","WEERT","WEESP","WEHE-DEN HOORN","WEHL","WEIDUM","WEITEVEEN","WEKEROM","WELL","WELSUM","WEMELDINGE","WENUM WIESEL","WERGEA","WERKENDAM","WERKHOVEN","WERNHOUT","WERVERSHOOF","WESEPE","WESSEM","WEST-GRAFTDIJK","WEST-TERSCHELLING","WESTBEEMSTER","WESTBROEK","WESTDORPE","WESTENDORP","WESTERBORK","WESTEREMDEN","WESTERGEAST","WESTERHAAR-VRIEZENVEENSEWIJK","WESTERHOVEN","WESTERLAND","WESTERVELDE","WESTERVOORT","WESTKAPELLE","WESTKNOLLENDAM","WESTMAAS","WESTZAAN","WEURT","WEZEP","WICHMOND","WIERDEN","WIERINGERWERF","WIERUM","WIJCHEN","WIJCKEL","WIJDENES","WIJDEWORMER","WIJHE","WIJK AAN ZEE","WIJK BIJ DUURSTEDE","WIJK EN AALBURG","WIJLRE","WIJNANDSRADE","WIJNGAARDEN","WIJNJEWOUDE","WIJSTER","WIJTHMEN","WILBERTOORD","WILDERVANK","WILHELMINADORP","WILHELMINAOORD","WILLEMSTAD NB","WILNIS","WILP","WINDESHEIM","WINKEL","WINSCHOTEN","WINSSEN","WINSUM","WINTELRE","WINTERSWIJK","WINTERSWIJK CORLE","WINTERSWIJK HUPPEL","WINTERSWIJK MISTE","WINTERSWIJK RATUM","WINTERSWIJK WOOLD","WIRDUM","WISSENKERKE","WITMARSUM","WITTEM","WITTEVEEN","WIUWERT","WOENSDRECHT","WOERDEN","WOGNUM","WOLDENDORP","WOLFHEZE","WOLPHAARTSDIJK","WOLVEGA","WOMMELS","WORKUM","WORMER","WORMERVEER","WOUBRUGGE","WOUDENBERG","WOUDRICHEM","WOUDSEND","WOUW","WOUWSE PLANTAGE","YERSEKE","YSBRECHTUM","YSSELSTEYN","ZP AMSTERDAM","ZAAMSLAG","ZAANDAM","ZAANDIJK","ZALTBOMMEL","ZANDPOL","ZANDVOORT","ZEDDAM","ZEELAND","ZEEWOLDE","ZEGGE","ZEGVELD","ZEIJEN","ZEIJERVELD","ZEIST","ZELHEM","ZENDEREN","ZETTEN","ZEVENAAR","ZEVENBERGEN","ZEVENBERGSCHEN HOEK","ZEVENHOVEN","ZEVENHUIZEN","ZIERIKZEE","ZIEUWENT","ZIJDERVELD","ZIJTAART","ZOELEN","ZOELMOND","ZOETERMEER","ZOETERWOUDE","ZOUTELANDE","ZOUTKAMP","ZUID-BEIJERLAND","ZUID-SCHARWOUDE","ZUIDBROEK","ZUIDDORPE","ZUIDERWOUDE","ZUIDHORN","ZUIDLAARDERVEEN","ZUIDLAND","ZUIDLAREN","ZUIDOOSTBEEMSTER","ZUIDVEEN","ZUIDVELDE","ZUIDWOLDE","ZUIDWOLDE DR","ZUIDZANDE","ZUNDERT","ZURICH","ZUTPHEN","ZWAAG","ZWAAGDIJK-OOST","ZWAAGDIJK-WEST","ZWAANSHOEK","ZWAMMERDAM","ZWANENBURG","ZWARTEMEER","ZWARTEWAAL","ZWARTSLUIS","ZWIJNDRECHT","ZWOLLE","DE LUTTE","DE WOUDE"])